spring.application.name=ip-geolocation-api

server.port=3000

geolocation.api.key=${API_KEY}
geolocation.api.base-url=https://api.ipgeolocation.io

geolocation.cache.file=${CACHE_FILE_PATH:data/ip-addrs.json}
